deployments:
  deploymentGating:
    enabled: true # to enable the feature
    retry: 50 # run poll action 50 times
    sleep: 30 # wait 30 seconds between each poll
    environments: # select the environments you'd like to use with this feature
    - Production
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlL2Y3NzU3ZjYzLThmNTYtNDk2My05Yzg0LTM0YThkYWE1NTk1ZC9jYzZhYmRiYy0wNTkzLTExZjAtYWY3Yy0wYWZmZjNkZDM0Nzc=
